server:
  port: 8888
spring:
  profiles:
    active: dev
  freemarker:
    cache: false
    request-context-attribute: request
  mvc:
    view:
      prefix: /templates/
      suffix: .ftl
# 启动 Redis 缓存
#  cache:
#    cache-names: redisCache
#    type: REDIS

  datasource:
    username: root
    password: yr19990418
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      default-transaction-isolation: 2
    dbcp2:
      default-transaction-isolation: 2

# Redis 配置
#  redis:
#    jedis:
#      pool:
#        max-active: 10    # 最大连接数
#        max-wait: 2000    # 最大等待毫秒
#        max-idle: 10      # 最大空闲数
#        min-idle: 5       # 最小空闲数
#    port: 6379
#    host: 127.0.0.1
#    timeout: 1000         # 连接超时时间，毫秒

  data:
    mongodb:
      database: springboot
      host: localhost
      port: 27017
      repositories:
        type: auto

logging:
  file:
    name: springboot.log
  level:
    com:
      yr:
        springboot: DEBUG
      jdbc: ERROR
      jdbc.resultsettable: ERROR
      org:
        mybatis: INFO
        springframework: INFO
        springframework.security: INFO
      root: INFO

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yr.springboot.demo05.mybatis.pojo
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true